import axios from 'axios';
import {
    demoGetLogs,
    demoGetShipments,
    demoGetStats,
    demoGetStatusOptions,
    demoLogin,
    demoUpdateAwb
} from './demoApi';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000';

export const isDemoMode = import.meta.env.VITE_DEMO_MODE === 'true';

const authHeaders = (token) => (
    token
        ? { Authorization: `Bearer ${token}` }
        : {}
);

export async function login(username, password) {
    if (isDemoMode) {
        return demoLogin(username, password);
    }

    const params = new URLSearchParams();
    params.append('username', username);
    params.append('password', password);

    const response = await axios.post(`${API_URL}/login`, params, {
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' }
    });

    return response.data;
}

export async function getStats(token) {
    if (isDemoMode) {
        return demoGetStats();
    }

    const response = await axios.get(`${API_URL}/stats`, {
        headers: authHeaders(token)
    });

    return response.data;
}

export async function getStatusOptions(token) {
    if (isDemoMode) {
        return demoGetStatusOptions();
    }

    const response = await axios.get(`${API_URL}/status-options`, {
        headers: authHeaders(token)
    });

    return response.data;
}

export async function updateAwb(token, payload) {
    if (isDemoMode) {
        return demoUpdateAwb(payload);
    }

    const response = await axios.post(`${API_URL}/update-awb`, payload, {
        headers: authHeaders(token)
    });

    return response.data;
}

export async function getLogs(token, params = {}) {
    if (isDemoMode) {
        return demoGetLogs(params);
    }

    const response = await axios.get(`${API_URL}/logs`, {
        params,
        headers: authHeaders(token)
    });

    return response.data;
}

export async function getShipments(token) {
    if (isDemoMode) {
        return demoGetShipments();
    }

    try {
        const response = await axios.get(`${API_URL}/shipments`, {
            headers: authHeaders(token),
            timeout: 5000 // Fail fast if backend is unreachable
        });
        return response.data;
    } catch (error) {
        console.warn("Backend API unavailable, attempting to load static snapshot...", error);
        try {
            // Fallback to static JSON generated by pull_postis_data.py
            // import.meta.env.BASE_URL handles the /arynik1/ prefix in production
            const snapshotUrl = `${import.meta.env.BASE_URL}data/shipments.json`.replace('//', '/');
            const response = await axios.get(snapshotUrl);
            console.info("Loaded shipments from static snapshot.");
            return response.data;
        } catch (snapshotError) {
            console.error("Failed to load both API and static snapshot", snapshotError);
            throw error; // Throw original error or new one
        }
    }
}
